### ISSUE TITLE
Sexuality self-identification

### ISSUE THREAD

**Issue by cherscarlett** [cherscarlett/pay-transparency-survey#2]
On the one hand, I'm not sure everyone would be comfortably identifying in this context. Does this make one easily identified by leadership? On the other hand, it is an important data point in representation and discrimination. 

One issue I see is that none of the companies I work for are tracking this as a diversity metric in published demographics. Does it make sense for us to start capturing to find any discrepancies as an argument for capturing that data more broadly in I&D?

Thoughts/discussion welcomed.

**Comment by johndoe9999999** [comment]
What a useful contribution to society :-)
